apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-workout-app
  labels:
    app: micro-workout-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micro-workout-app
  template:
    metadata:
      labels:
        app: micro-workout-app
    spec:
      containers:
        - name: micro-workout-app
          image: 418295691381.dkr.ecr.us-east-1.amazonaws.com/micro-workout-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
