apiVersion: v1
kind: Service
metadata:
  name: micro-workout-service
spec:
  type: LoadBalancer
  selector:
    app: micro-workout-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
